"""ISP data for "Why is my [ISP] internet slow?" pages.

Researched 2026-10-06 from primary sources only (ISP support, outage and gateway pages,
ISP/parent press releases). Each entry lists the URLs used in "sources". Anything that could
not be confirmed from a primary source is marked UNVERIFIED rather than guessed.

Fields per ISP: slug, name, parent, connection_types, outage_url, outage_notes, speed_test_url,
gateway, admin_address, app, restart_steps, bridge_mode, own_equipment, asymmetry,
slowdown_causes, slow_speed_help_url, recommended_steps, support_url, notes, sources.
"""

ISPS = [
    {
        "slug": "spectrum",
        "name": "Spectrum",
        "parent": "Charter Communications",
        "connection_types": [
            "cable (DOCSIS, hybrid fiber-coax)",
            "fiber (select areas)"
        ],
        "outage_url": "https://www.spectrum.net/support/internet/troubleshooting-your-spectrum-services-after-outage",
        "outage_notes": "Spectrum's outage page sends you to chat or a Check Outages button; area outage details are tied to your account (sign in at Spectrum.net or use the My Spectrum App). In the My Spectrum App you can turn on push alerts for outages (More > Settings > Notifications > Manage > Support > Outages). Spectrum also runs a Storm Center page for weather events.",
        "speed_test_url": "https://www.spectrum.com/internet/speed-test",
        "gateway": "Spectrum usually supplies a separate modem plus a WiFi router rather than one combo box. Current Advanced WiFi routers (WiFi 5, 6, 6E and 7) have model numbers starting with SAC2V1A, SAC2V2S, SAX1V1R, SAX1V1K, SAX1V1S, SAX2V1S, SAX2V1R, SBE1V1K or SBE1V1R. Only the WiFi 6E and WiFi 7 models (SAX2V1R, SAX2V1S, SBE1V1K) support 6 GHz. Older supported routers listed by Spectrum include the Arris TG1672G, Askey, Netgear 3800/6300, Sagemcom (incl. 5260), Technicolor TC8717T and Ubee DVW32CB.",
        "admin_address": "Depends on the router, per Spectrum's WiFi setup article: 192.168.1.1 (Askey, Sagemcom, Sagemcom 5260), 192.168.0.1 (Arris TG1672G, Technicolor TC8717T, Ubee DVW32CB) and www.routerlogin.net (Netgear 3800/6300). Spectrum Advanced WiFi routers are managed through the My Spectrum App or your Spectrum.net account (Services > Internet).",
        "app": "My Spectrum App",
        "restart_steps": [
            "Online: sign in at Spectrum.net, open the Services tab and then the Internet sub-tab, choose your equipment and select Restart Equipment (you can also do this in the My Spectrum App).",
            "Manual (coax customers only): unplug the power cord from the modem and from the WiFi router.",
            "Wait at least one minute, then reinsert any batteries and plug the modem back in.",
            "Wait at least two more minutes while the modem powers on. Its lights should gradually come on.",
            "Plug the WiFi router back in and give it at least two minutes to finish starting up.",
            "Open two or three different web pages to make sure the connection works.",
            "Fiber customers: Spectrum says not to touch the back of the fiber modem, because that can damage the fiber cable."
        ],
        "bridge_mode": "UNVERIFIED: Spectrum does not publish a bridge-mode procedure. In the usual setup the modem is a separate box with no router built in, so you can use your own router by plugging it into the modem in place of Spectrum's router (Spectrum says you can rent their router or buy your own).",
        "own_equipment": "Allowed, with limits. You can use a modem you own if it is on Spectrum's authorized retail list. There are separate lists for non-symmetrical tiers up to 1G and up to 500 Mbps, plus a 'minimally qualified' list that Spectrum advises against. Spectrum technicians support only Spectrum-provided equipment. Customer-owned modems do not work with Spectrum Home Phone, and they are allowed only on non-symmetrical tiers: equal-speed customers must use a Spectrum D3.1 modem. Spectrum provides a compliant modem at no extra charge. You can rent a Spectrum WiFi router for a monthly fee or buy your own.",
        "asymmetry": "Most standard tiers have much slower upload than download. Spectrum's broadband disclosure lists Spectrum Internet 500 at 500 Mbps x 20 Mbps, Spectrum Internet 1 Gig at 1,000 Mbps x 35 Mbps, and Internet Assist at 50 x 10 Mbps. In select locations Spectrum sells equal ('symmetrical') speeds: Internet 500 up to 300/300 Mbps, Ultra up to 500/500 Mbps and 1 Gig up to 1/1 Gbps. 2 Gig (typical 2,056 down / 1,002 up) and 7 Gig (typical 7,454 down / 7,813 up) are also offered in certain locations. One national label for Internet 100 shows typical 116 Mbps down / 105 Mbps up and 19 ms latency, so upload speeds differ by market and network upgrade status.",
        "slowdown_causes": [
            "Peak-time congestion on the shared neighborhood cable segment (common to DOCSIS cable networks; not specifically stated by Spectrum)",
            "Low upload capacity on non-symmetrical tiers (e.g. 20-35 Mbps up), which can bottleneck video calls, cloud backups and uploads",
            "An older or uncertified modem that can't deliver your tier: Spectrum keeps an authorized-modem list and offers equipment upgrades when speeds rise",
            "Loose or damaged coax and power cables (Spectrum's troubleshooting starts by checking cables)",
            "Device-side factors Spectrum lists: file-sharing programs (BitTorrent), viruses/adware/malware, strict firewalls, low system memory (RAM), outdated browser, power-save/low-power mode",
            "WiFi limits: Spectrum recommends an 802.11n router for speeds up to 300 Mbps and 802.11ac for speeds above 300 Mbps; 2.4 GHz reaches farthest but is slowest, 6 GHz is fastest but has the shortest range",
            "Too many devices in use at once (Spectrum advises disconnecting devices not in use)"
        ],
        "slow_speed_help_url": "https://www.spectrum.net/support/internet/slow-internet-speeds",
        "recommended_steps": [
            "Update your device to the latest operating system and browser.",
            "Take a speed test, ideally from a computer wired to the modem with a Cat 5e or better Ethernet cable.",
            "Check for file-sharing programs, malware (Spectrum offers Security Suite), an overly strict firewall, low RAM and power-save mode.",
            "Disconnect devices that aren't in use and restart your computer or device.",
            "Make sure your router suits your speed (802.11n up to 300 Mbps, 802.11ac above 300 Mbps) and that you use a 1 Gbps full-duplex network card.",
            "Restart your modem online (Spectrum.net or the My Spectrum App), or manually: unplug the modem and router, wait 1 minute, power the modem on and wait 2 minutes, then power the router on and wait 2 minutes.",
            "Restart the router by pressing and holding its reset button for five seconds.",
            "If problems continue, contact Spectrum (chat or phone)."
        ],
        "support_url": "https://www.spectrum.net/contact-us",
        "notes": "Spectrum's disclosure lists data as Unlimited, with no charges for extra data. Charter completed its acquisition of Cox Communications on August 20, 2026. Spectrum branding, pricing and packaging are rolling out in former Cox markets, and Spectrum's support site now shows a 'Cox is now Spectrum' banner.",
        "sources": [
            "https://www.spectrum.net/support/internet/slow-internet-speeds",
            "https://www.spectrum.net/support/internet/troubleshooting-your-spectrum-services-after-outage",
            "https://www.spectrum.net/support/internet/compliant-modems-charter-network",
            "https://www.spectrum.net/support/internet/connect-to-wifi-network",
            "https://www.spectrum.net/support/internet/adaptive-steering",
            "https://www.spectrum.net/support/internet/symmetrical-or-equal-download-and-upload-speeds",
            "https://www.spectrum.com/policies/spectrum-broadband-disclosure",
            "https://labels.bcl.spectrum.com/RESI-SAD4-S-NAT1Y-EN.html",
            "https://www.spectrum.com/internet/speed-test",
            "https://www.spectrum.net/contact-us",
            "https://corporate.charter.com/newsroom/charter-and-cox-communications-complete-transaction"
        ]
    },
    {
        "slug": "xfinity",
        "name": "Xfinity",
        "parent": "Comcast",
        "connection_types": [
            "cable (DOCSIS, hybrid fiber-coax)",
            "fiber (select communities)"
        ],
        "outage_url": "https://www.xfinity.com/support/statusmap",
        "outage_notes": "The Xfinity Outage Map asks you to sign in for details about your service. Outage updates are also available in the Xfinity app and through Xfinity Assistant, which can find outages and run diagnostics.",
        "speed_test_url": "https://www.xfinity.com/learn/internet-service/speed-test",
        "gateway": "Xfinity WiFi Gateway, an all-in-one modem and router. Models in Xfinity's user manuals: XB3, XB6, XB7, XB8, XB9 and XB10. Also listed: the Xfinity WiFi Router XER10, the XE2 WiFi Extender and the XD4 Advanced Modem.",
        "admin_address": "http://10.0.0.1 (Xfinity Admin Tool). You first have to allow access in the Xfinity app: WiFi tab > View WiFi equipment > Advanced settings > Admin Tool online access > Allow, then Save. The username is admin, and the password is the one you create when you enable access. People who enabled access before February 2026 may still use the default password on the gateway's sticker.",
        "app": "Xfinity app",
        "restart_steps": [
            "In the Xfinity app (rented gateways): open the WiFi section, tap Troubleshoot, then select Restart your Gateway.",
            "Or run the same troubleshooting from Xfinity Assistant or xfinity.com on a computer.",
            "Manual: unplug the gateway's power cable, wait one minute and plug it back in.",
            "The restart can take up to 12 minutes, and your home network won't work in the meantime. With Xfinity Voice, you can't make or receive calls (including 911) until the gateway is back online."
        ],
        "bridge_mode": "Yes. Bridge Mode turns off the gateway's routing and leaves the modem running so you can use your own router. You enable it in the Admin Tool at http://10.0.0.1 under Gateway > At a Glance > Bridge Mode: Enable (Admin Tool access may need to be allowed in the Xfinity app first). Caveats: only one device can connect to the gateway in Bridge Mode. You can't manage your network in the app or use WiFi Extenders, and Bridge Mode won't turn on if extenders are already activated. Xfinity CyberSecure access is blocked.",
        "own_equipment": "Allowed if the device works with Xfinity and supports your speed. Check it in My Device Info (sign in or enter your address). Most modems need a separate router for WiFi. You are responsible for installing it, keeping it updated and troubleshooting it, and unsupported devices won't work. Customer-owned modems don't currently work with X-Class (equal upload/download) speeds. Only a few retail devices support the faster upload speeds in upgraded 'enhanced' areas. Xfinity Prepaid and NOW Internet equipment doesn't work with regular Xfinity Internet. In fiber-delivered communities, any standard router that supports your speed tier can be used.",
        "asymmetry": "Upload depends on whether your area has been upgraded. On the standard network upload is far below download: Xfinity's Gigabit article lists download up to 1000 Mbps (1200 in some areas) and upload up to 35 Mbps. Since 2022 Xfinity has been moving areas to 'enhanced speed' status with 5-10x faster uploads (75-200 Mbps). X-Class tiers offer equal upload and download above 200 Mbps in limited areas.",
        "slowdown_causes": [
            "Peak-time congestion on the shared neighborhood cable segment (common to DOCSIS cable networks; not specifically stated by Xfinity)",
            "Low upload capacity on non-upgraded areas/tiers (as low as ~35 Mbps up on Gigabit), which bottlenecks uploads and video calls",
            "Many family members and devices using WiFi at the same time (cited by Xfinity)",
            "Devices joining a public xfinitywifi/XFINITY hotspot instead of your home network (cited by Xfinity)",
            "Distance from the gateway, and interference from nearby networks, walls, metal, microwaves, cordless phones, baby monitors and Bluetooth devices (cited by Xfinity)",
            "Loose coaxial cable connections (Xfinity says to tighten the coax as much as possible)",
            "An owned modem that isn't certified for your speed tier or for enhanced upload speeds",
            "Outdated devices or operating systems; for Gigabit, wired speeds top out around 940 Mbps over Ethernet (cited by Xfinity)"
        ],
        "slow_speed_help_url": "https://www.xfinity.com/support/articles/internet-connectivity-troubleshooting",
        "recommended_steps": [
            "Use the Xfinity app (WiFi > Troubleshoot) or Xfinity Assistant to check for outages and run diagnostics.",
            "Check several devices to see whether the problem affects one device or the whole network.",
            "Try a few different apps or websites to rule out a problem with a single service.",
            "Make sure you're within WiFi range of the gateway or router.",
            "Confirm the equipment cables are plugged in and the coaxial cable is fully tightened.",
            "Run a speed test on a single device to check download and upload speeds.",
            "Make sure devices are on your home network, not an xfinitywifi hotspot, and not paused or blocked in the Xfinity app.",
            "Plug high-bandwidth devices into the gateway with Ethernet. Place the gateway centrally, upright and off the floor, away from interference.",
            "Restart the gateway (app or unplug for one minute). If the problem can't be fixed online, schedule a technician."
        ],
        "support_url": "https://www.xfinity.com/support/contact-us",
        "notes": "Xfinity says its current internet plans have no data caps. Legacy plans may still have a 1.2 TB monthly limit, and accounts over that limit may be charged for extra data. The latest Xfinity plans include the Xfinity Gateway at no extra cost.",
        "sources": [
            "https://www.xfinity.com/support/articles/internet-connectivity-troubleshooting",
            "https://www.xfinity.com/support/articles/improve-your-wireless-home-network",
            "https://www.xfinity.com/support/articles/troubleshooting-your-cable-modem",
            "https://www.xfinity.com/support/articles/wireless-gateway-enable-disable-bridge-mode",
            "https://www.xfinity.com/support/articles/admin-tool-access",
            "https://www.xfinity.com/support/articles/list-of-approved-cable-modems",
            "https://www.xfinity.com/support/articles/upgraded-areas-leased-equipment-required-for-upload-speeds",
            "https://www.xfinity.com/hub/internet/faster-upload-speeds",
            "https://www.xfinity.com/support/articles/get-most-from-xfinity-gigabit-internet-service",
            "https://www.xfinity.com/support/articles/usermanuals",
            "https://www.xfinity.com/hub/internet/data-caps",
            "https://www.xfinity.com/support/statusmap",
            "https://www.xfinity.com/learn/internet-service/speed-test",
            "https://www.xfinity.com/support/contact-us"
        ]
    },
    {
        "slug": "att",
        "name": "AT&T",
        "parent": "AT&T Inc.",
        "connection_types": [
            "fiber (AT&T Fiber, FTTH)",
            "copper / IPBB (AT&T Internet, fiber-to-the-node over phone lines)",
            "DSL (legacy copper, no longer sold)"
        ],
        "outage_url": "https://www.att.com/outages/",
        "outage_notes": "The outage page requires sign-in (or a one-time code sent to a phone number on the account) to see outages for your address or account. AT&T also points customers to the Smart Home Manager app/online tool to check Wi-Fi issues and outages.",
        "speed_test_url": "https://www.att.com/support/speedtest/",
        "gateway": "AT&T-provided Wi-Fi gateway. AT&T lists common models as BGW320, BGW210, Pace 5268, NVG599 and NVG589; the BGW320 is branded the 'All-Fi Hub' (Wi-Fi 6, used on AT&T Fiber multi-gig plans) and the BGW620 is also supported by Smart Home Manager. Legacy DSL customers may have an AT&T-compatible DSL modem instead.",
        "admin_address": "192.168.1.254 (AT&T: enter http://192.168.1.254 in a browser to reach the gateway user interface on any AT&T Wi-Fi gateway)",
        "app": "AT&T Smart Home Manager app (also usable online from a computer)",
        "restart_steps": [
            "Unplug the power cord from the back of the gateway/All-Fi Hub and the wall (remove the internal battery backup if it has one).",
            "Wait 20 seconds, then reinsert the battery if applicable.",
            "Plug the power cord back in and wait for the gateway to restart; it can take up to five minutes for it and your devices to come back online.",
            "Alternative: in the Smart Home Manager app, select Network (Wi-Fi icon) > Restart Wi-Fi and confirm.",
            "Do not confuse with Reset: holding the red Reset button for 15+ seconds restores factory defaults and erases custom Wi-Fi names and passwords."
        ],
        "bridge_mode": "AT&T Fiber/AT&T Internet gateways do not offer a documented true bridge mode for residential service; instead they support IP Passthrough. AT&T's residential steps for BGW210/BGW320/Pace 5268: go to http://192.168.1.254 > Firewall > Advanced (enter the Device Access Code), turn off the advanced firewall options, then IP Passthrough with Allocation Mode = Passthrough and Passthrough Mode = DHCPS-fixed, enter the MAC address of your router, save and restart. AT&T's business documentation notes only one device can be in passthrough, it loses the AT&T gateway's firewall protection, and it gets the WAN IP. Legacy DSL modems (e.g. Westell) can be set to true bridge mode with the router doing PPPoE.",
        "own_equipment": "For AT&T Fiber and AT&T Internet, the AT&T gateway is AT&T-provided equipment (\"We provide the gateway when you set up internet at your home\") and must be returned on cancellation; you cannot replace it, but you can put your own router behind it (ideally via IP Passthrough). For legacy AT&T DSL, AT&T documents connecting a non-AT&T router to the DSL modem using PPPoE/bridge mode. AT&T Tech Support only supports routers from AT&T.",
        "asymmetry": "Differs by connection type. AT&T Fiber: all tiers are symmetrical (\"equal upload and download speeds\"); tiers are 300 Mbps, 500 Mbps, up to 1 GIG, 2 GIG and 5 GIG. AT&T Internet over copper (IPBB) and DSL: asymmetrical, with upload far below download (e.g. IPBB Internet 100 is advertised as 100 Mbps down / 20 Mbps up per AT&T's broadband performance disclosure); AT&T describes DSL as suitable only for light use such as browsing or email.",
        "slowdown_causes": [
            "Copper (AT&T Internet/DSL): speed is impacted by the distance between your home and the central office (AT&T 'Understand Internet Speeds').",
            "Age of the wiring inside your building (copper).",
            "On copper, TV and internet sharing the same line reduces the bandwidth available for internet.",
            "Wi-Fi is slower than wired Ethernet, and Wi-Fi speed is shared among all devices connected to the gateway.",
            "Distance from the gateway and obstructions (walls, doors, floors, concrete or rebar), plus interference from microwaves, baby monitors and other Wi-Fi networks.",
            "Older devices, and devices with more than one radio like phones and tablets, may not reach faster speeds.",
            "Many simultaneous activities: multiple devices, streaming, gaming, video conferencing, smart home devices.",
            "Website server capacity and routing outside AT&T's network."
        ],
        "slow_speed_help_url": "https://www.att.com/support/how-to/optimize-your-connection/",
        "recommended_steps": [
            "Check for an outage at att.com/outages (sign-in required).",
            "Check the status lights on your Wi-Fi gateway or All-Fi Hub.",
            "Restart the gateway (unplug for 20 seconds, wait up to 5 minutes).",
            "Run the AT&T speed test on your device and on the gateway (att.com/support/speedtest).",
            "Reduce the number of devices and heavy activities (streaming, gaming, video calls) running at once.",
            "Move closer to the gateway or remove obstructions and interference sources; use a wired connection where possible.",
            "Consider newer devices, since older devices may not reach faster speeds."
        ],
        "support_url": "https://www.att.com/support/contact-us/",
        "notes": "AT&T no longer offers DSL service to new customers (att.com/internet/dsl). Data allowances: AT&T Internet tiers 768Kbps-75Mbps get 1.5TB/month; Internet 100 and higher (incl. AT&T Fiber) are unlimited; legacy DSL gets 150GB/month; overage is $10 per 50GB, capped at $100/month for AT&T Internet and $200 for DSL. UNVERIFIED: AT&T has announced plans to exit its copper network in most of its wireline footprint by end of 2029 (about.att.com page seen in search but returned 403 to fetch).",
        "sources": [
            "https://www.att.com/outages/",
            "https://www.att.com/support/speedtest/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1010340/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1010361/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1010095/",
            "https://www.att.com/support/how-to/optimize-your-connection/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1011652/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1206322/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1394673/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1322413/",
            "https://www.att.com/support/smallbusiness/article/smb-internet/KM1188700/",
            "https://www.att.com/support/smallbusiness/article/smb-internet/KM1197962/",
            "https://www.att.com/support/article/dsl-high-speed/KM1044640/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1008461/",
            "https://www.att.com/support/article/u-verse-high-speed-internet/KM1010099/",
            "https://www.att.com/internet/gigabit-speed-test-results/",
            "https://www.att.com/internet/dsl/",
            "https://www.att.com/internet/smart-home/",
            "https://www.att.com/support/contact-us/",
            "https://about.att.com/sites/broadband/performance"
        ]
    },
    {
        "slug": "verizon-fios",
        "name": "Verizon Fios",
        "parent": "Verizon Communications",
        "connection_types": [
            "fiber (FTTH, Fios)"
        ],
        "outage_url": "https://www.verizon.com/support/residential/service-outage",
        "outage_notes": "Verizon's outage information page routes customers to Service Central, which requires signing in to My Verizon; outages for your address appear as a network notification there. The My Verizon app is also offered.",
        "speed_test_url": "https://www.verizon.com/speedtest/",
        "gateway": "Verizon Router (models CR1000A and CR1000B, Wi-Fi 6E tri-band 2.4/5/6 GHz) on current plans; older installs have the Fios Router (G3100) or the Fios Quantum Gateway (G1100).",
        "admin_address": "192.168.1.1 or myfiosgateway.com (username 'admin', password on the router's rear label), per Verizon Router FAQs and Fios Router FAQs.",
        "app": "Verizon Home app (router management: restart, speed test, Wi-Fi networks; rolled out to select routers from Aug 2024). Account management is in the My Verizon app, which replaced the My Fios app on Nov 29, 2023.",
        "restart_steps": [
            "Unplug the router.",
            "Wait 1 minute.",
            "Plug the router back in.",
            "Wait 1-3 minutes for initialization to complete, then try connecting again.",
            "Alternative (Verizon Router CR1000A/B): press and hold the Reset button on the back for 3-5 seconds and wait for the Internet light to turn steady white. Holding it for 15 seconds is a factory reset.",
            "Alternative: restart the router from the Verizon Home app."
        ],
        "bridge_mode": "UNVERIFIED: no official Verizon support page found documenting bridge mode or IP passthrough for Fios routers (Verizon's IP Passthrough/Bridge Mode article, knowledge-base-301824, covers the 'Verizon Internet Gateway' used for 5G/LTE Home Internet, not Fios). Common practice is to plug your own router directly into the ONT instead.",
        "own_equipment": "UNVERIFIED: no official Verizon support page found that states the policy. Verizon's router FAQs do not address it, and Verizon's community forums (now redirected to the main support site) indicated you can use your own router if the ONT delivers internet over Ethernet, Verizon supports only up to the ONT, and Fios TV set-top boxes need a Verizon router or MoCA workaround. Verizon says a Wi-Fi 6E router is included with all plans.",
        "asymmetry": "Nearly symmetrical. Verizon says Fios provides 'nearly symmetrical upload and download speeds'; plans are 300 Mbps, 500 Mbps, 1 Gig, 2 Gig and 5 Gig. Fios Gigabit is quoted at average wired download speeds of 750-940 Mbps with comparable upload.",
        "slowdown_causes": [
            "Wi-Fi vs. wired: Verizon notes a Wi-Fi speed test measures your Wi-Fi network, not the broadband speed delivered to the home.",
            "2.4 GHz band has greater range but lower max speed (Verizon cites 75 Mbps); 5 GHz is faster with less range.",
            "Interference from other Wi-Fi networks, Bluetooth, cordless phones, microwaves, baby monitors, mirrors, and physical obstructions.",
            "WEP security can reduce speed by up to 80%; use WPA2.",
            "VPNs can slow your connection.",
            "Multiple devices streaming at once and many devices sharing the connection.",
            "Device limits: processor, memory, OS; gigabit speeds require a capable wired device.",
            "Quality and condition of the wiring connecting your computers to the Verizon network.",
            "Network outages or slow website servers."
        ],
        "slow_speed_help_url": "https://www.verizon.com/support/residential/internet/connectivity/slow-speed/",
        "recommended_steps": [
            "Run the Verizon speed test (verizon.com/speedtest) or use the app's Wi-Fi Health Check > Speed Test.",
            "For an accurate test, connect a computer directly to the router with Ethernet, disconnect VPNs, and stop other devices and streaming during the test.",
            "If on Wi-Fi, move your device closer to the router.",
            "Remove other devices from the network and close other applications.",
            "Reboot the router.",
            "Use Verizon's Guided Solutions tool (Fix Slow Internet) for further troubleshooting.",
            "Place the router centrally and away from interference; use 5 GHz for important devices; use WPA2 not WEP; consider a Fios Network Extender for dead zones."
        ],
        "support_url": "https://www.verizon.com/support/",
        "notes": "Verizon's community forum links now redirect to the main support site (community sunset). The 'My Fios' app was folded into My Verizon on Nov 29, 2023; router control moved to the separate Verizon Home app.",
        "sources": [
            "https://www.verizon.com/support/residential/service-outage",
            "https://www.verizon.com/speedtest/",
            "https://www.verizon.com/support/residential/internet/connectivity/slow-speed/",
            "https://www.verizon.com/support/residential/internet/connectivity/wi-fi",
            "https://www.verizon.com/support/residential/internet/connectivity/no-connection",
            "https://www.verizon.com/support/residential/internet/equipment/routers/verizon-router",
            "https://www.verizon.com/support/residential/internet/equipment/routers/fios-router/",
            "https://www.verizon.com/content/dam/verizon/support/consumer/documents/internet/fios-router-user-guide.pdf",
            "https://www.verizon.com/content/dam/verizon/support/consumer/documents/internet/verizon-router-guide.pdf",
            "https://www.verizon.com/support/knowledge-base-149095/",
            "https://www.verizon.com/support/knowledge-base-301824/",
            "https://www.verizon.com/support/verizon-home-app-faqs/",
            "https://www.verizon.com/home/internet/fios-fastest-internet/faq/",
            "https://www.verizon.com/support/residential/internet/getting-started/fios-gigabit",
            "https://www.verizon.com/support/"
        ]
    },
    {
        "slug": "verizon-5g-home",
        "name": "Verizon 5G Home Internet",
        "parent": "Verizon Communications",
        "connection_types": [
            "5G fixed wireless (5G Ultra Wideband / 5G)",
            "4G LTE (LTE Home in some locations)"
        ],
        "outage_url": "https://www.verizon.com/support/check-network-status/",
        "outage_notes": "Verizon's network status tool: select the Home Internet tab, enter your address or use your location, then Check now. If you sign in to My Verizon and Verizon knows of an outage in your area, a Network Notification alert shows at the top of the screen.",
        "speed_test_url": "https://www.verizon.com/speedtest/",
        "gateway": "Verizon Internet Gateway (ARC-XCI55AX, ASK-NCQ1338, ASK-NCQ1338FA, ASK-NCM1100, WNC-CR200A), Verizon 5G Internet Gateway (LVSKIHP), Verizon 5G Home Router (LVSKR1), Verizon Receiver (LV65), Verizon Router (CR1000A/CR1000B). Verizon's support pages list these models; which one you get depends on your plan and area.",
        "admin_address": "mynetworksettings.com, or https://192.168.1.1 (WNC-CR200A and ARC-XCI55AX) / https://192.168.0.1 (ASK-NCQ1338 and ASK-NCQ1338FA), per Verizon's 'Verizon Internet Gateway - Access Admin Page' article. Browsers may show a certificate warning; the admin password is on the label on the bottom of the router.",
        "app": "Verizon Home app (speed test, Gateway 5G Optimizer); restarts can also be done from the My Verizon app",
        "restart_steps": [
            "Restart the router from the My Verizon app or My Verizon online (Verizon's 5G Home support overview).",
            "Or unplug the router for 30 seconds, then plug it back in (Verizon's 'What is slowing my internet down?' guide).",
            "Restart your devices, and check that power and Ethernet cables are plugged in and undamaged."
        ],
        "bridge_mode": "Supported on the Verizon Internet Gateway as IP Passthrough: Admin page > Advanced > Network Settings > Network Connections > Network (Home/Office) > Settings > Bridge section > check IP Passthrough > Save. The router reboots (1-2 minutes). Your own router then plugs into the LAN2 Ethernet port and gets the network-assigned IP. All Wi-Fi radios turn off, and the internet no longer works over Wi-Fi or LAN1. To turn it off, connect a device to LAN1, sign in to the admin web UI and uncheck IP Passthrough.",
        "own_equipment": "The Verizon Internet Gateway is required. Verizon owns it and you must return it within 30 days of cancelling or pay an unreturned equipment fee. Verizon's IP passthrough article says you can connect your own router, switch or other network gear behind the gateway through its LAN2 port.",
        "asymmetry": "Very asymmetric. From Verizon's Important Plan Information: 5G Home up to 100 Mbps: 25-85 Mbps typical download / 5-10 Mbps upload. 5G Home up to 300 Mbps: 85-300 down / 10-20 up. 5G Home Plus up to 500 Mbps: 200-500 down / 20-35 up. 5G Home Ultimate up to 1 Gig: 300-1000 down / 25-75 up. LTE Home: 25-50 down / 4-5 up. Uploads may go over 5G and 4G LTE when the signal is weaker.",
        "slowdown_causes": [
            "Weak 5G signal at the gateway's location. Verizon recommends a window or wall facing the tower, on a higher floor, away from cabinets and metal (Gateway 5G Optimizer article).",
            "Network congestion. 5G Home and LTE Home lines that use more than the Heavy Data User threshold (1.83 TB in a billing month as of June 2026) may have their data prioritized behind other traffic during congestion for the rest of the cycle (Verizon Important Plan Information, Network Management).",
            "Disconnections when the connection switches between cell towers, or when bad weather disrupts service (Verizon's 'What is slowing my internet down?' guide).",
            "Uploads may fall back to 4G LTE when the signal is weaker (Important Plan Information).",
            "Speeds vary with address/location, equipment, network connection and outside factors affecting cellular networks (Important Plan Information).",
            "Home Wi-Fi problems: interference from Bluetooth devices, microwaves and baby monitors, too many connected devices, or a VPN (Verizon Wi-Fi slow-connection FAQs)."
        ],
        "slow_speed_help_url": "https://www.verizon.com/home/internet/guides/what-is-slowing-my-internet-down/",
        "recommended_steps": [
            "Restart your router and modem: unplug them for 30 seconds and plug them back in.",
            "Restart your devices.",
            "Check all cables and connections.",
            "Run a speed test at Verizon.com (or in the Verizon Home app). If speeds are low, repeat steps 1-3.",
            "Check Verizon's network status tool for an outage at your address.",
            "Use the Gateway 5G Optimizer in the Verizon Home app to find the spot with the strongest 5G signal.",
            "If there's no outage and it's still not working, contact Verizon Support."
        ],
        "support_url": "https://www.verizon.com/support/5g-home-internet/",
        "notes": "Verizon's 5G Home marketing says 'no data limits', but the network management policy applies: lines over 1.83 TB/month (as of June 2026) may be deprioritized during congestion. Service may only be used at the registered service address. Verizon's general contact page is https://www.verizon.com/support/contact-us/ (it redirects to a contact app).",
        "sources": [
            "https://www.verizon.com/support/5g-home-internet/",
            "https://www.verizon.com/support/verizon-5g-home-router-troubleshooting/",
            "https://www.verizon.com/support/5g-internet-gateway/",
            "https://www.verizon.com/support/knowledge-base-301456/",
            "https://www.verizon.com/support/knowledge-base-301824/",
            "https://www.verizon.com/support/knowledge-base-312043/",
            "https://www.verizon.com/support/network-outage-faqs/",
            "https://www.verizon.com/support/check-network-status/",
            "https://www.verizon.com/speedtest/",
            "https://www.verizon.com/support/important-plan-information/",
            "https://www.verizon.com/support/broadband-services/",
            "https://www.verizon.com/support/5g-home-faqs/",
            "https://www.verizon.com/support/residential/internet/connectivity/wi-fi",
            "https://www.verizon.com/home/internet/guides/what-is-slowing-my-internet-down/",
            "https://www.verizon.com/support/contact-us/"
        ]
    },
    {
        "slug": "t-mobile-home-internet",
        "name": "T-Mobile Home Internet",
        "parent": "T-Mobile US",
        "connection_types": [
            "5G fixed wireless",
            "4G LTE fixed wireless"
        ],
        "outage_url": "https://www.t-mobile.com/support/coverage/network-outages",
        "outage_notes": "T-Mobile has no public outage map for Home Internet. Its Network Outages page explains outage notifications (tower maintenance or unplanned problems) and says T-Mobile will tell you when the outage is fixed, usually within two days. You may need to power cycle the gateway afterward. The T-Life app's diagnostics check the gateway's connection to the T-Mobile network.",
        "speed_test_url": "",
        "gateway": "5G Gateway Gen5 (G5AR, G5SE), 5G Gateway Gen4 (G4AR, G4SE). Older gateways: Sagemcom FAST 5688W, Arcadyan KVD21, Nokia 5G21, Askey LTE Wi-Fi Gateway.",
        "admin_address": "http://192.168.12.1 is documented only for older gateways (Arcadyan KVD21 and Nokia 5G21 support pages). The login is on the label on the underside of the gateway. T-Mobile directs Gen4/Gen5 gateway settings to the T-Life app; UNVERIFIED whether Gen4/Gen5 gateways have a browser admin page.",
        "app": "T-Life app",
        "restart_steps": [
            "Unplug the gateway from power, wait 30 seconds, then plug it back in. Allow 2 minutes for it to fully reconnect before testing (T-Mobile Troubleshooting page).",
            "Or in the T-Life app: go to the Overview screen, check that the gateway is online, select Restart your gateway, and wait for it to restart.",
            "Don't restart the gateway while it is updating. It restarts on its own when the update finishes (5G Gateway Gen5 page)."
        ],
        "bridge_mode": "Not supported. T-Mobile states that its gateways can't turn bridge mode on or off.",
        "own_equipment": "A T-Mobile gateway is required (service runs through the SIM in the gateway). Third-party routers can connect to the gateway's Ethernet port. Both the gateway and the third-party router will broadcast Wi-Fi unless you turn off the gateway's Wi-Fi in the T-Life app. Mesh systems and switches can also be connected.",
        "asymmetry": "Very asymmetric. T-Mobile's Home Internet FAQ: All-In or Amplified Home Internet typically 170-498 Mbps download and 12-55 Mbps upload. Rely Home Internet typically 170-354 Mbps download and 12-55 Mbps upload. 25% of customers see speeds below these ranges and 25% above. There are no speed tiers.",
        "slowdown_causes": [
            "Deprioritization: T-Mobile's network management disclosure says Home Internet customers generally get the same network priority as Mobile Wireless Heavy Data Users. Customers may notice slower speeds than higher-priority customers during congestion. Where the network is heavily loaded they will likely see significant drops in speed, especially for data-intensive activities.",
            "Heavy use: since May 8, 2024, Internet customers who use more than 1.2TB in a billing cycle become Internet Heavy Data Users and are prioritized last on the network. The status resets at the next bill cycle.",
            "The FAQ says that during congestion, Internet customers may see slower speeds than customers on other T-Mobile services, and slower still above 1.2TB/month, because of data prioritization.",
            "Speeds vary with location, time of day, signal strength and availability (Home Internet FAQ). Weak signal at the gateway's location: use the T-Life app to check signal and find the best placement.",
            "Home Wi-Fi interference: microwaves, baby monitors, Bluetooth devices, fluorescent lights and large metal appliances near the gateway; distance and walls.",
            "Internet Lite plans: slowdowns once the data allowance is used up."
        ],
        "slow_speed_help_url": "https://www.t-mobile.com/support/home-internet/customer-support",
        "recommended_steps": [
            "Run a network diagnostics test in the T-Life app (it checks the gateway's Wi-Fi and its connection to the T-Mobile network).",
            "Restart the gateway: unplug it, wait 30 seconds, plug it back in, and allow 2 minutes before testing.",
            "Check which Wi-Fi band your device uses. Create a 2.4GHz network for devices that are far away or older.",
            "Reduce interference near the gateway (microwaves, baby monitors, Bluetooth devices, fluorescent lights, large metal appliances).",
            "Move any mesh unit to a central, open, mid-height spot.",
            "On an Internet Lite plan, check your data usage.",
            "Use the T-Life app to check signal and find the best placement for the gateway.",
            "Move the device to within 15 feet of the gateway, and restart connected devices.",
            "Run a speed test at Speedtest.net to confirm the gateway is getting good network speeds.",
            "If it's still slow, contact T-Mobile."
        ],
        "support_url": "https://www.t-mobile.com/support/home-internet/contact-us",
        "notes": "Home Internet support phone (from T-Mobile's site): 1-844-275-9310. T-Mobile's Network Traffic Prioritization & Management page (URL redirects to /responsibility/consumer-info/policies/internet-service/network-management-practices) says stationary Home Internet customers 'should be less likely to notice congestion in general.' T-Mobile has no official speed test page of its own; its troubleshooting page points to Speedtest.net. AWAY plan: speeds drop to 128kbps once the monthly data is used.",
        "sources": [
            "https://www.t-mobile.com/support/home-internet/customer-support",
            "https://www.t-mobile.com/home-internet/policies/internet-service/network-management-practices",
            "https://www.t-mobile.com/responsibility/consumer-info/policies/internet-service/network-management-practices",
            "https://www.t-mobile.com/home-internet/faq",
            "https://www.t-mobile.com/support/home-internet/connect",
            "https://www.t-mobile.com/support/home-internet/app",
            "https://www.t-mobile.com/support/home-internet/t-mobile-gateway",
            "https://www.t-mobile.com/support/home-internet/5g-gateway-g5",
            "https://www.t-mobile.com/support/home-internet/arcadyan-gateway",
            "https://www.t-mobile.com/support/home-internet/nokia-gateway",
            "https://www.t-mobile.com/support/coverage/network-outages",
            "https://www.t-mobile.com/support/home-internet/contact-us"
        ]
    },
    {
        "slug": "cox",
        "name": "Cox",
        "parent": "Charter Communications (acquired Aug 20, 2026; now branded Spectrum)",
        "connection_types": [
            "cable (DOCSIS, hybrid fiber-coax)",
            "fiber (some homes, via ONT)"
        ],
        "outage_url": "https://www.cox.com/residential/support/outages.html",
        "outage_notes": "This page is now branded 'Spectrum Outage Information'. You check status by entering your address or signing in. You can sign up for outage text alerts in MyAccount or the Cox App by Spectrum. Cox says there is a Spectrum outage map, and SmartHelp (after you sign in) shows details for your address, including an estimated restoration time. During an outage, Cox says not to reset your equipment.",
        "speed_test_url": "https://www.cox.com/residential/support/internet/speedtest.html",
        "gateway": "Panoramic Wifi Gateway, a modem and router in one (WiFi 5 or WiFi 6). Example: the Technicolor CGM4981, a DOCSIS 3.1 tri-band WiFi 6 Panoramic Wifi Gateway that supports up to the Go Beyond Fast 2 Gig tier.",
        "admin_address": "192.168.0.1 (Panoramic Wifi Gateway Admin Tool). The username is admin, and the password is on the gateway's bottom label; if that doesn't work, try 'password'.",
        "app": "Cox App by Spectrum (account, SmartHelp, modem reset) and the Cox Panoramic Wifi app (WiFi management and whole-home speed test)",
        "restart_steps": [
            "In the Cox app: sign in, find your equipment under My Services, tap Reset Modem in the My Internet section, then tap Begin reset. The reboot can take up to ten minutes, and Cox Voice is briefly interrupted.",
            "Manual: turn off devices using the internet, then unplug the modem's power cord (and the router's, if you use one).",
            "Check that the coax cable is tight at the wall and the modem, and check any Ethernet cables.",
            "Plug the modem back in and allow up to ten minutes for it to come online, then plug the router back in."
        ],
        "bridge_mode": "Yes, on the Panoramic Wifi Gateway. Go to the Admin Tool at 192.168.0.1 > Gateway > At a Glance > Bridge Mode: Enable, confirm, and the gateway restarts. Then connect your router to any gateway Ethernet port. Caveats: you can't use Panoramic Wifi features or Pods, and Bridge Mode can't be turned on if Pods are activated. It isn't compatible with MoCA services such as IPTV or Cox Homelife, or with fiber-delivered service (homes with an ONT). To turn it off again, your device must be wired to the gateway by Ethernet.",
        "own_equipment": "Allowed. You can buy a retail modem from Cox's compatible/certified modem list, but you'll also need your own router for WiFi. Cox now says device support is limited to equipment rented or bought from Spectrum, and you lose the Panoramic Wifi perks. Combination internet and telephone modems bought new or used from third-party retailers are not certified for the Cox network.",
        "asymmetry": "UNVERIFIED: Cox's own tier-by-tier upload speeds are no longer published. Cox's speeds-and-data-plans disclosure now redirects to Spectrum's broadband disclosure, which lists Spectrum Internet 500 at 500 x 20 Mbps and 1 Gig at 1,000 x 35 Mbps, so upload is much lower than download on standard cable tiers. Fiber-delivered homes and 2 Gig tiers are the exception.",
        "slowdown_causes": [
            "Peak-time congestion on the shared neighborhood cable segment (common to DOCSIS cable networks; not specifically stated by Cox)",
            "An older modem: Cox says slow speeds can come from an older modem and points you to its certified modem list",
            "Loose coax or Ethernet cables, or an Ethernet cable older than Cat5e (Cox recommends at least Cat5e)",
            "Many devices using the connection at once (Cox's first step is to turn devices off)",
            "Testing over WiFi or through a separate router instead of wired to the modem (Cox says to test wired to the modem/gateway and not through a router)",
            "Gateway placement: Cox recommends a central location about 3 feet or higher, not in a cabinet or closet",
            "Low upload capacity on standard cable tiers relative to download"
        ],
        "slow_speed_help_url": "https://www.cox.com/residential/support/troubleshooting-slow-internet-speeds.html",
        "recommended_steps": [
            "Make sure your modem isn't outdated (check Cox's certified cable modems).",
            "Turn off devices that are using the internet (computers, phones, tablets, game consoles).",
            "Unplug the modem's power cord, and the router's if you use one.",
            "Check that the coax cable is tight at the wall and the modem, and that Ethernet cables (Cat5e or better) go to the router's Ethernet/IN/WAN port.",
            "Plug the modem back in and allow up to ten minutes, then plug the router back in.",
            "Turn on one computer, clear the browser cache and cookies, and run a speed test. Panoramic Wifi users can test in the Panoramic Wifi app; others should test wired directly to the modem, not through a router, with no other devices online.",
            "If it's still slow, try other devices to see whether the problem is one device or the whole household, then contact support."
        ],
        "support_url": "https://www.cox.com/residential/contactus.html",
        "notes": "Charter completed its acquisition of Cox on August 20, 2026. Spectrum branding, pricing and packaging launched in Cox markets in mid-September 2026, and cox.com now shows 'Cox is now Spectrum'. Some Cox support pages, such as the speeds-and-data-plans disclosure, now redirect to or reuse Spectrum content. UNVERIFIED: the current data usage policy for former Cox customers (the Cox data usage meter requires sign-in).",
        "sources": [
            "https://www.cox.com/residential/support/internet.html",
            "https://www.cox.com/residential/support/troubleshooting-slow-internet-speeds.html",
            "https://www.cox.com/residential/support/outages.html",
            "https://www.cox.com/residential/support/understanding-panoramic-wifi.html",
            "https://www.cox.com/residential/support/enabling-bridge-mode-on-the-panoramic-wifi-gateway.html",
            "https://www.cox.com/residential/support/technicolor-cgm4981.html",
            "https://www.cox.com/residential/internet/learn/using-cox-compatible-modems.html",
            "https://www.cox.com/residential/support/rebooting-your-equipment-with-the-cox-app.html",
            "https://www.cox.com/residential/support/internet/speedtest.html",
            "https://www.cox.com/residential/contactus.html",
            "https://www.cox.com/aboutus/policies/speeds-and-data-plans.html",
            "https://www.spectrum.com/policies/spectrum-broadband-disclosure",
            "https://corporate.charter.com/newsroom/charter-and-cox-communications-complete-transaction"
        ]
    },
    {
        "slug": "optimum",
        "name": "Optimum",
        "parent": "Optimum Communications, Inc. (formerly Altice USA; corporate name changed effective November 7, 2025)",
        "connection_types": [
            "cable (HFC / DOCSIS)",
            "fiber (FTTH)"
        ],
        "outage_url": "https://www.optimum.net/support/outage/",
        "outage_notes": "Requires sign-in: Optimum says to go to optimum.net, sign in with your Optimum ID and password, then under Support (upper right) select Service status / Check for outages. Optimum's FAQ also points to an outage map.",
        "speed_test_url": "https://www.optimum.com/internet/speed-test",
        "gateway": "Optimum-provided Gateway (all-in-one modem and router). Install guides exist for 'Gateway 4' and 'Gateway 5' (the Gateway 4 guide label shows Ubee P/N UBC1322BA00). Fiber customers get a 'Fiber Gateway' (WiFi 6) that replaces the modem and router. Optimum One / Optimum TV boxes can also restart the gateway.",
        "admin_address": "Optimum documents web portals rather than a local IP: sign in at optimum.net/gateway (per Gateway 4/5 install guides) or router.optimum.net (Smart Router settings FAQ). Local LAN IP address: UNVERIFIED.",
        "app": "My Optimum app (WiFi > More options > Manage router settings; also WiFi > Troubleshoot my Internet)",
        "restart_steps": [
            "In the My Optimum app: sign in with your Optimum ID, tap WiFi > More options > Manage router settings, then tap Restart my Internet equipment. The restart takes about 5 minutes.",
            "Or chat with Allie, Optimum's 24/7 virtual assistant, to have your equipment restarted remotely (about 5 minutes).",
            "Manually: unplug the power cord from your Gateway or modem (remove the battery backup if you have one, and unplug your router if you have one).",
            "Wait 30 seconds.",
            "Plug the power cord back in (reinsert the battery backup and plug the router back in if applicable).",
            "Try to access the Internet as you normally do.",
            "With an Optimum One or Optimum TV box: Home > Settings > System > INTERNET/WIFI AND PHONE > REBOOT, or hold the diamond button on the box's front panel for 10 seconds until 'GW Reset' appears."
        ],
        "bridge_mode": "UNVERIFIED (no Optimum support page found documenting bridge or passthrough mode on the Optimum Gateway).",
        "own_equipment": "Yes for cable modems. Internet-only customers (no Optimum phone) can use their own DOCSIS-certified DOCSIS 3.1 modem or gateway; Optimum does not allow DOCSIS 2.0 or 3.0 modems. Customer-owned modems get no Optimum tech support or replacement, and you must call 877.694.9474 to activate one. Renting a modem costs 'as low as $15 per month' per the certified-modems page (Optimum's FAQ page says rentals start at $10/month). Optimum also says to make sure your own modem can handle your plan speed. Using your own router with Optimum Fiber: UNVERIFIED.",
        "asymmetry": "Cable (HFC) plans are asymmetric: Optimum's own comparison lists cable upload speeds of 5 Mbps to 35 Mbps, even on plans with much faster downloads. Fiber plans are symmetric, up to 8 Gbps download / 8 Gbps upload on the 8 Gig plan.",
        "slowdown_causes": [
            "Wi-Fi rather than wired: Optimum says testing over Wi-Fi will almost always show slower speeds than a wired Ethernet connection.",
            "Distance and obstructions between device and Gateway, and interference from baby monitors, cordless phones, Bluetooth devices or wireless cameras (Optimum WiFi tips).",
            "Too many devices sharing bandwidth, plus background apps and automatic updates (Optimum articles).",
            "Latency, jitter and packet loss can make the connection feel slow even when a speed test looks fine (Optimum article).",
            "Outdated operating systems, drivers or firmware, and older devices that cannot handle faster speeds (Optimum WiFi tips).",
            "A customer-owned modem that cannot handle the plan speed. Optimum requires DOCSIS 3.1, and after a speed upgrade you may need to reset the modem or set up new equipment.",
            "An aging gateway: Optimum suggests upgrading equipment if your gateway is several years old.",
            "VPNs, which Optimum says can cut speeds by 30-50%.",
            "UNVERIFIED: congestion on the shared neighborhood cable node at peak hours (typical of cable networks; not stated on an Optimum page)."
        ],
        "slow_speed_help_url": "https://www.optimum.com/articles/internet/fast-speed-test-slow-internet",
        "recommended_steps": [
            "Check all cables and make sure your modem and router are powered (Optimum internet support article).",
            "Restart your Gateway/modem and router: unplug, wait 30 seconds, plug back in.",
            "Check for outages: sign in at optimum.net > Support > Service status, or look for service alerts in the app.",
            "Test on more than one device. If only one device is affected, toggle its Wi-Fi off and on, move it closer to the Gateway, or restart it.",
            "Use a wired Ethernet connection for demanding tasks, and for the most accurate speed test.",
            "Limit background apps and pause automatic updates, and disconnect devices you are not using.",
            "Put the router or Gateway in a central, open, elevated spot away from interference.",
            "Run the My Optimum app's WiFi > Troubleshoot my Internet flow.",
            "Contact support, who can do a remote system reset of your modem or Gateway."
        ],
        "support_url": "https://www.optimum.com/contact-us",
        "notes": "Optimum says it has no data caps (fiber plan page; Optimum vs. Xfinity comparison). Altice USA changed its corporate name to Optimum Communications, Inc. effective Nov 7, 2025, and its NYSE ticker from ATUS to OPTU. Where Fiber is not available, service runs over cable connected to Optimum's fiber network (Optimum FAQ). Support phone per Optimum's support article: 877.694.9474.",
        "sources": [
            "https://faq.optimum.net/node/13581",
            "https://faq.optimum.net/node/13121",
            "https://faq.optimum.net/node/13396",
            "https://faq.optimum.net/node/13576",
            "https://faq.optimum.net/node/7342",
            "https://faq.optimum.net/node/7343",
            "https://www.optimum.net/support/outage/",
            "https://www.optimum.net/pages/optimum-certified-modems.html",
            "https://www.optimum.net/pages/wifitips.html",
            "https://www.optimum.net/pages/speedtest.html",
            "https://www.optimum.net/pages/fiber.html",
            "https://www.optimum.net/cdn/static.tvlistings.optimum.net/ool/static/prod/documents/user-guides/Gateway_4_Install_Guide.pdf",
            "https://www.optimum.net/cdn/static.tvlistings.optimum.net/ool/static/prod/documents/user-guides/Gateway_5_Install_Guide.pdf",
            "https://www.optimum.com/internet/speed-test",
            "https://www.optimum.com/internet/fiber",
            "https://www.optimum.com/faqs",
            "https://www.optimum.com/articles/internet/fast-speed-test-slow-internet",
            "https://www.optimum.com/articles/internet/optimum-internet-support",
            "https://www.optimum.com/articles/internet/optimum-vs-xfinity",
            "https://www.optimum.com/contact-us",
            "https://www.optimum.com/about-us/news/articles/altice-usa-changes-corporate-name-and-nyse-ticker-symbol-align-optimum-brand"
        ]
    },
    {
        "slug": "frontier",
        "name": "Frontier",
        "parent": "Verizon Communications (Frontier became a wholly owned subsidiary of Verizon when the acquisition closed on January 20, 2026)",
        "connection_types": [
            "fiber (FTTH)",
            "DSL (copper)"
        ],
        "outage_url": "https://frontier.com/pages/helpcenter/internet/troubleshooting/check-for-service-outages",
        "outage_notes": "The online checker requires sign-in (you enter your service address). No sign-in needed: text OUTAGE to 70994 and Frontier will text updates until the outage is resolved. Outages can also be checked under Support in the MyFrontier app.",
        "speed_test_url": "https://speedtest.frontier.com/",
        "gateway": "Fiber: Amazon eero routers. Fiber 500, 1 Gig and 2 Gig plans get the eero Pro 7; Fiber 5 Gig and 7 Gig get the eero Max 7 (both Wi-Fi 7). Fiber customers also have an ONT (Optical Network Terminal). Older and DSL routers named in Frontier docs: Arris NVG443B, NVG448B, NVG448BQ, NVG468MQ and NVG589; Netgear 7550 and D2200D; Actiontec F2250, GT784WNV and WR424; Greenwave G1100; Pace 4111N, 5031NV and 5168NV; D-Link DSL 2750B.",
        "admin_address": "eero: managed in the eero app (opened from the MyFrontier app), not via a browser IP. Other Frontier routers, per Frontier's help page: 192.168.254.254 (Arris NVG443B/448B/448BQ/468MQ, Netgear D2200D, Netgear 7550); 192.168.1.254 (Arris NVG589, Pace 4111N/5031NV/5168NV); 192.168.0.1 (Actiontec F2250, GT784WNV, WR424); 192.168.1.1 (D-Link DSL 2750B, Greenwave G1100).",
        "app": "MyFrontier app (eero Wi-Fi settings open in the eero app from inside MyFrontier)",
        "restart_steps": [
            "Router, gateway or modem: unplug the unit.",
            "Wait 30 seconds.",
            "Plug it back in and give it a few minutes to fully power up.",
            "Fiber ONT: if a battery backup unit is attached, remove one of the battery leads so it stops powering the ONT. Unplug the ONT, wait at least five minutes, then plug it back in, and make sure the ONT lights are on."
        ],
        "bridge_mode": "UNVERIFIED (no Frontier help page found documenting bridge or passthrough mode on the eero or other Frontier routers). Frontier fiber delivers service through an ONT, and Frontier says you can replace its router after activation (see own_equipment).",
        "own_equipment": "You must use the Frontier router or modem the first time you activate service. After that you may replace the Frontier router with one you buy, but Frontier says it 'only supports the routers we supply to you'. With a non-Frontier router, Frontier may not be able to manage some or all of your services, remote troubleshooting and support will be limited, and the router may not be compatible.",
        "asymmetry": "Fiber is symmetric: Fiber 500 (500/500), 1 Gig (1000/1000), 2 Gig (2000/2000), 5 Gig (5000/5000) and 7 Gig (7000/7000). DSL is asymmetric: Frontier says the most common DSL type gives download much more bandwidth than upload because most users download more than they upload.",
        "slowdown_causes": [
            "DSL: landline phones without DSL filters. Phones should plug into the filter's 'Phone' port and the modem into the 'DSL' port (Frontier support wizard).",
            "VPN software. Frontier suggests testing without the VPN and says that if the connection improves, the VPN is likely the problem.",
            "Bandwidth-heavy devices (streaming movies, high-intensity gaming) and background updates on other devices.",
            "Wi-Fi interference from other electronics, walls and doors, and nearby Wi-Fi networks on the same channel. Restarting the router makes it rescan for the least congested channel.",
            "Distance from the router, and older devices or older Wi-Fi technology.",
            "A plan with too little bandwidth for the number of users and devices.",
            "Inside wiring at the premises and network congestion (Frontier internet disclosures).",
            "UNVERIFIED: DSL speeds dropping with copper line length or distance from the central office (not stated on a Frontier page found)."
        ],
        "slow_speed_help_url": "https://frontier.com/helpcenter/categories/support-wizard/internet/slow-internet-connection",
        "recommended_steps": [
            "Reboot your equipment: unplug the unit, wait 30 seconds, plug it back in and give it a few minutes to fully power up.",
            "Check whether you are using a VPN, and test for a while without it.",
            "Pause bandwidth-heavy activity such as streaming movies or high-intensity gaming on other devices.",
            "DSL (non-Fiber) customers: make sure DSL filters are installed on landline phones, with phones on the 'Phone' port and the modem on the 'DSL' port.",
            "Run a speed test, preferably over a wired connection with VPNs, backups and streaming turned off.",
            "If problems continue, contact Frontier Technical Support."
        ],
        "support_url": "https://frontier.com/contact-us",
        "notes": "Verizon's acquisition of Frontier closed January 20, 2026. A Frontier wholesale bulletin says Frontier is now a wholly owned subsidiary of Verizon, integration is expected to continue through the end of 2026, and support contacts and products are unchanged for now. Fiber plans advertise no data caps. Frontier's contact page offers 24/7 chat for technical issues; the residential tech support phone number was not confirmed (UNVERIFIED). Frontier says its speed test measures 'speed to device', which Wi-Fi and device limits affect, and that maximum speeds are wired.",
        "sources": [
            "https://frontier.com/helpcenter/categories/support-wizard/internet/slow-internet-connection",
            "https://frontier.com/helpcenter/internet/how-to-use-your-frontier-router",
            "https://frontier.com/helpcenter/internet/how-to-optimize-your-wifi",
            "https://frontier.com/helpcenter/internet/troubleshooting/how-to-troubleshoot-your-ont",
            "https://frontier.com/helpcenter/internet/why-your-speed-tests-may-not-match-your-plan",
            "https://frontier.com/helpcenter/internet/change-wifi-network-name-and-password",
            "https://frontier.com/pages/helpcenter/internet/troubleshooting/check-for-service-outages",
            "https://frontier.com/offer/eero",
            "https://frontier.com/resources/what-is-dsl-internet",
            "https://frontier.com/corporate/internet-disclosures/residential-internet",
            "https://frontier.com/corporate/internet-disclosures/residential-fiberoptic",
            "https://frontier.com/contact-us",
            "https://go.frontier.com/fiber/internet",
            "https://speedtest.frontier.com/",
            "https://wholesale.frontier.com/dcaas-staticassets/wholesale/SourceFiles/2026Notifications/CCBFTR02379_Verizon_Frontier_Acquisition_Closed_01202026.pdf",
            "https://www.verizon.com/about/sites/default/files/verizon-4Q25-earnings-press-release.pdf"
        ]
    },
    {
        "slug": "centurylink",
        "name": "CenturyLink / Quantum Fiber",
        "parent": "Lumen Technologies (CenturyLink copper/DSL). Quantum Fiber and Lumen's consumer fiber-to-the-home business in 11 states were sold to AT&T; the sale closed February 2, 2026.",
        "connection_types": [
            "DSL (ADSL / ADSL2+ / VDSL, including pair-bonded lines)",
            "fiber (FTTH)"
        ],
        "outage_url": "https://www.centurylink.com/home/help/internet/internet-or-phone-not-working.html",
        "outage_notes": "Requires sign-in: when you sign in to My CenturyLink on the web or in the app, you see an alert if you are affected by an outage, and you can sign up for outage notifications there. The automated Troubleshooter tool also tests your line and equipment. CenturyLink says to always reboot your modem after an outage.",
        "speed_test_url": "https://www.centurylink.com/home/help/internet/internet-speed-test.html",
        "gateway": "CenturyLink gateways (all-in-one modem/router). Current recommended models: C4000 (C4000LG/LZ for ADSL/ADSL2+/VDSL, C4000BG/BZ for bonded-pair DSL, C4000XG for fiber), C3510XZ (fiber) and C3000. Other certified models in use: C2300A, C5500XK Fiber SmartNID, PK5000Z, C424G, C844G. CenturyLink Fiber with Premium WiFi uses a wall-mounted SmartNID plus WiFi pods.",
        "admin_address": "http://192.168.0.1 (modem settings GUI). Sign in with the Admin Username and Admin Password printed on the modem sticker.",
        "app": "My CenturyLink app (shows outage alerts, can restart the modem, and manages Premium WiFi). Quantum Fiber customers use the Quantum Fiber app.",
        "restart_steps": [
            "Unplug the power cord from the back of the modem or from the wall outlet, and check that all the modem lights go off.",
            "Wait 30 seconds to 1 minute (at least 30 seconds so the modem memory fully clears).",
            "Plug the power cord back in and wait for the power and internet lights to turn green (or the single status light on the C4000). A full boot can take 3-5 minutes.",
            "Alternatively, in the My CenturyLink app go to Services and tap the restart modem button (top tasks area or the Equipment section). On the web, go to My CenturyLink > Services > Equipment > your modem > Restart Modem.",
            "Fiber with Premium WiFi: unplug the SmartNID power cord, wait at least 30 seconds, plug it back in and wait 2-3 minutes. Do not remove the fiber cords from the SmartNID."
        ],
        "bridge_mode": "Yes, called transparent bridging. On newer CenturyLink modems, set Transparent Bridging in the Advanced Setup > WAN Settings of the modem GUI. You must chat with tech support to get the transport mode (VLAN setting) for your area, and it is not available in all areas. CenturyLink warns not to change WAN settings unless a CenturyLink technician or IT professional tells you to.",
        "own_equipment": "Allowed, with caveats. A third-party modem must support VLAN tagging 201, and modems from cable internet providers do not work. CenturyLink says most third-party modems don't work, or don't work well, and it publishes no list of compatible third-party models. You get only limited tech support, no equipment replacement, and you need PPPoE username/password and VPI/VCI from chat. Technicians install new service with a CenturyLink modem; you can return it afterward if your own modem works. Re-using a newer CenturyLink modem that is compatible with your connection type and speed is likely to work.",
        "asymmetry": "CenturyLink says that on DSL plans the download speed tends to be much higher than the upload speed, while fiber often offers symmetrical speeds. Tested DSL speeds on the C4000: ADSL up to 7 Mbps, ADSL2+ up to 20 Mbps, VDSL up to 100 Mbps, and bonded pairs up to 40 Mbps (ADSL2+) or 140 Mbps (VDSL). Fiber tested up to 940 Mbps. CenturyLink DSL is marketed at up to 100 Mbps.",
        "slowdown_causes": [
            "A problem on the DSL line itself. CenturyLink says to check the Downstream Rate in Modem Status at 192.168.0.1: if it is well below your plan speed, it is a service issue that may need a technician; if it is close, the cause is likely Wi-Fi, household traffic or devices.",
            "Missing DSL filters on landline phones when you have both internet and CenturyLink home phone, or a loose DSL cord (often green) between the wall jack and the modem's DSL port.",
            "A modem that has been running a long time and needs a reboot (which also lets it pick the least-interfered Wi-Fi channel), or outdated modem firmware.",
            "Wi-Fi 'piggybacking' by neighbors on a weakly secured network.",
            "Interference from microwaves, cordless phones, Bluetooth devices, TVs and baby monitors, plus physical obstacles such as large appliances and metal or glass objects.",
            "Older devices that cannot reach high speeds and can slow the whole network, and always-on devices running background updates.",
            "Peak hours when more household members are online, and busy content providers or web hosts.",
            "Rural locations, which CenturyLink says often get slower speeds than urban centers.",
            "UNVERIFIED: DSL speed falling with distance from the central office or loop length (not stated on a CenturyLink page found)."
        ],
        "slow_speed_help_url": "https://www.centurylink.com/home/help/internet/modems-and-routers/troubleshoot-slow-internet.html",
        "recommended_steps": [
            "Check your connection status: sign in to the modem settings GUI and compare the Downstream Rate in Modem Status to your plan speed.",
            "Reboot your modem.",
            "Make sure your WiFi network is secured with a strong password.",
            "For fiber, make sure you have the right equipment for fiber speeds.",
            "Improve Wi-Fi: reduce interference and move the router away from obstacles and dense appliances.",
            "Check devices: older devices, background updates, malware and too many running applications can slow things down.",
            "Check cables: the DSL cord should be in a working phone jack and the modem's DSL port, and DSL filters should be on all landline phones.",
            "Try a wired Ethernet connection directly to the modem.",
            "Run a speed test and compare it to your plan speed in My CenturyLink.",
            "If speeds stay below your plan, run the automated Troubleshooter (which can open a repair ticket and schedule a technician) or contact a support agent."
        ],
        "support_url": "https://www.centurylink.com/home/help/contact.html",
        "notes": "AT&T completed its acquisition of substantially all of Lumen's Mass Markets fiber business, including Quantum Fiber, on February 2, 2026 ($5.75B; more than 1 million fiber subscribers across more than 4 million locations in 11 states). Lumen says it kept its copper-based consumer services, so CenturyLink DSL stays with Lumen. Quantum Fiber's site says it is 'now part of the AT&T family' and that existing customers keep their equipment and manage service in the same Quantum Fiber app/portal. Quantum Fiber-specific support URLs were not researched. CenturyLink advertises unlimited data and no data caps on DSL. Contact page offers 7-day chat; phone numbers shown are region-dependent (800-244-1111 and 800-201-4099).",
        "sources": [
            "https://www.centurylink.com/home/help/internet/modems-and-routers/troubleshoot-slow-internet.html",
            "https://www.centurylink.com/home/help/internet/modems-and-routers/reboot-your-modem.html",
            "https://www.centurylink.com/home/help/internet/modems-and-routers/modem-status.html",
            "https://www.centurylink.com/home/help/internet/modems-and-routers/compatible-modems.html",
            "https://www.centurylink.com/home/help/internet/modems-and-routers/third-party-modem-support-and-settings.html",
            "https://www.centurylink.com/home/help/internet/modems-and-routers/advanced-setup/wan-settings.html",
            "https://www.centurylink.com/home/help/internet/internet-or-phone-not-working.html",
            "https://www.centurylink.com/home/help/internet/internet-speed-test.html",
            "https://www.centurylink.com/home/help/internet/internet-speed-test/speed-test-faqs.html",
            "https://www.centurylink.com/home/help/internet/fiber/premium-wifi/troubleshooting.html",
            "https://www.centurylink.com/home/help/account/app.html",
            "https://www.centurylink.com/home/help/contact.html",
            "https://www.centurylink.com/internet/dsl-internet-service.html",
            "https://investors.att.com/~/media/Files/A/ATT-IR-V2/documents/att-lumen-deal-close-press-release.pdf",
            "https://ir.lumen.com/news/news-details/2026/Lumen-Completes-Sale-of-Consumer-Fiber-to-the-Home-Business-to-ATT/default.aspx",
            "https://ir.lumen.com/news/news-details/2025/Lumen-Technologies-Advances-Enterprise-Market-Focus-with-Sale-of-Consumer-Fiber-to-the-Home-Business-to-ATT/default.aspx",
            "https://www.quantumfiber.com/att-offer.html"
        ]
    },
    {
        "slug": "google-fiber",
        "name": "Google Fiber (GFiber)",
        "parent": "Alphabet Inc. (GFiber; combination with Stonepeak's Astound Broadband announced March 11, 2026, expected to close Q4 2026)",
        "connection_types": [
            "fiber (FTTH)"
        ],
        "outage_url": "https://gfiber.com/outage/check/",
        "outage_notes": "Public tool: enter your street address to see network status, no sign-in needed. Outages also appear in the Network section of the gFiber App and as a red banner in the online account portal. Text START to 434237 for SMS outage updates.",
        "speed_test_url": "https://gfiber.com/speedtest/",
        "gateway": "gFiber-supplied router plus a Fiber Jack (ONT, model GFLT100). Current routers: Wi-Fi 7 Router (GRBE331C, included with Home 3 Gig and Edge 8 Gig), Wi-Fi 6E Router (GR6EXX0C, included with Core 1 Gig), Wi-Fi 6 Router (GRAX210T), Multi-Gig Router (GFRG300). Mesh extenders: Wi-Fi 7 (GEBE320C), Wi-Fi 6E (GE6E220C). Older installs may have Nest Wifi Pro, Google Wifi or the legacy Network Box (no longer supported).",
        "admin_address": "192.168.1.1 (gFiber: the router's LAN IP is 'typically 192.168.1.1'). gFiber directs settings changes to the gFiber App or the online account portal rather than a local web page.",
        "app": "gFiber App (Google Home app also supported for network monitoring)",
        "restart_steps": [
            "Unplug the power cord.",
            "Wait at least 10 seconds.",
            "Plug the power cord back in.",
            "Wait up to 5 minutes for the device to turn back on (Wi-Fi 6E/Wi-Fi 7 router light goes solid green; Wi-Fi 6 router solid blue).",
            "Alternative: tap Restart router in the gFiber App and confirm."
        ],
        "bridge_mode": "Yes. In the gFiber App: Network > Advanced network settings > Edit router settings > toggle Bridge mode on, with your router's WAN port connected to the gFiber router's 10 Gbps LAN port. Intended for the Multi-Gig Router (GFRG300) when there is no separate wall-mounted Fiber Jack, or custom setups; it turns off the gFiber router's Wi-Fi, routing and mesh extenders. Otherwise plug your own router straight into the Fiber Jack.",
        "own_equipment": "Yes. Connect a third-party router to the Fiber Jack's Ethernet port. gFiber recommends a 1 Gbps WAN port and Wi-Fi 6 for 1 Gig, a 10 Gbps WAN port with Wi-Fi 6E/7 for 2-5 Gig, and a 10 Gbps WAN port with Wi-Fi 7 for 8 Gig, plus Cat6 or better cable. Support covers the signal to the Fiber Jack only, not third-party router setup, and the gFiber App can't manage a third-party router.",
        "asymmetry": "Symmetrical: 'your max download and upload speeds will match your service.' Plans: Core 1 Gig, Home 3 Gig (up to 3,000 Mbps both ways), Edge 8 Gig.",
        "slowdown_causes": [
            "Wi-Fi: gFiber says it is unlikely you will hit full gigabit speeds over Wi-Fi; wired Ethernet is fastest.",
            "Router placement and obstacles (concrete, metal, brick; to a lesser extent drywall, wood, thick glass) and interference from microwaves and baby monitors.",
            "Older devices and browsers max out at lower speeds; multi-gig needs Wi-Fi 6E/7 capable devices.",
            "VPNs: speed is capped by how fast the VPN server can process data.",
            "Concurrent streaming (e.g. 4K) using much of the bandwidth.",
            "Peak hours (7-11 PM) congestion on external websites and servers outside gFiber's control.",
            "Poorly placed or too many mesh extenders."
        ],
        "slow_speed_help_url": "https://gfiber.com/support/en/answer/1916/",
        "recommended_steps": [
            "Check for an outage (gFiber App, outage tool, or account portal); if there is one, no troubleshooting is needed.",
            "Check for account or payment alerts that could pause service.",
            "Run a gFiber speed test, ideally over a wired Ethernet connection.",
            "Temporarily disconnect from any VPN and retest.",
            "Update device software or test with a newer device.",
            "Restart the router (unplug 10 seconds, wait up to 5 minutes) or restart via the gFiber App.",
            "Place the router centrally, elevated, in the open; put mesh extenders halfway to the weak area.",
            "Check network health in the gFiber App."
        ],
        "support_url": "https://gfiber.com/support/",
        "notes": "Rebranded from Google Fiber to GFiber (support moved from support.google.com/fiber to gfiber.com/support). No data caps, overage charges or throttling per gFiber FAQ. On March 11, 2026, GFiber and Stonepeak's Astound Broadband announced they will combine; Stonepeak will be majority owner with Alphabet a significant minority shareholder, expected close Q4 2026.",
        "sources": [
            "https://gfiber.com/support",
            "https://gfiber.com/support/en/answer/124",
            "https://gfiber.com/support/en/answer/1916/",
            "https://gfiber.com/support/en/answer/1103/",
            "https://gfiber.com/support/en/answer/1833/",
            "https://gfiber.com/support/en/answer/1951/",
            "https://gfiber.com/support/en/answer/1952/",
            "https://gfiber.com/outage/check/",
            "https://gfiber.com/speedtest/",
            "https://gfiber.com/support/en/answer/1816/",
            "https://gfiber.com/support/en/answer/1924/",
            "https://gfiber.com/support/en/answer/1857/",
            "https://gfiber.com/faq/",
            "https://gfiber.com/rebrand/fiber.googleblog.com/2026/03/gfiber-and-stonepeaks-astound-to.html"
        ]
    },
    {
        "slug": "starlink",
        "name": "Starlink",
        "parent": "SpaceX",
        "connection_types": [
            "low-Earth-orbit satellite"
        ],
        "outage_url": "",
        "outage_notes": "Starlink has no public outage status page. Outages show in the Starlink app as a SERVICE OUTAGE alert ('Your area is currently experiencing a service outage'). The app home screen also shows alerts for obstructions and hardware problems, and the Statistics page shows outages. US residential customers who are offline can call 1-866-606-5103 (a 24/7 trial phone line).",
        "speed_test_url": "",
        "gateway": "Starlink Router 3 (included with the Standard/V4 kit), Router Mini, Gen 2 Router, Gen 1 Router. The dish connects to the router by the Starlink cable.",
        "admin_address": "The Starlink Router has no administrator portal. All router settings are in the Starlink app (per Starlink's 'Does Starlink have a WiFi router administrator portal?' article). The Starlink device dashboard is at http://192.168.100.1. With a third-party router you need a static route (192.168.100.0/24 via WAN) to reach it.",
        "app": "Starlink app (iOS/Android): speed tests including Advanced Speed Test, alerts, obstruction checks, Wi-Fi settings, reboot",
        "restart_steps": [
            "Reboot from the Starlink app (Reboot is one of the router settings in the app).",
            "Or power cycle Starlink and the router by unplugging the AC cable from the wall outlet and plugging it back in (Starlink's 'Slow Speeds - Outside/During Peak Hours' article)."
        ],
        "bridge_mode": "Yes. Router 3 and Router Mini support Bypass Mode: Starlink app > Settings > Bypass Mode > Enable. This turns off the Starlink router's Wi-Fi so a third-party router plugged into its Ethernet port runs the network. A violet light shows for 1 hour. The only way to exit bypass mode is a factory reset. Kits with a power supply that has built-in Ethernet (Performance Gen 1/Gen 2, Enterprise) don't need bypass; plug the router into the power supply. On Gen 1 Router kits, replace the Starlink router.",
        "own_equipment": "The Starlink dish is required. Most kits support a third-party router over Ethernet (Standard: Ethernet built into the power supply; Standard Actuated needs the Starlink Ethernet Adapter plus Bypass Mode; Mini uses the USB-C to Ethernet adapter). Set the router's WAN to DHCP. Starlink offers only limited troubleshooting for non-Starlink equipment and suggests removing third-party gear when testing speeds.",
        "asymmetry": "Very asymmetric. Starlink's support/specs search results show typical downloads of roughly 45-280 Mbps and uploads of 10-30 Mbps. UNVERIFIED: these numbers come from starlink.com search results and were not confirmed on a fetched page (the specifications page didn't render speeds). Residential 100 Mbps and 200 Mbps plans cap download at the number in the plan name (Service Plan Descriptions).",
        "slowdown_causes": [
            "Obstructions: trees, buildings, new leaves in spring, debris or snow on the dish. These cause interruptions that are most noticeable on video calls and gaming (app alerts and 'How to fix obstructions').",
            "Peak-hour congestion, typically 6pm-11pm local time, when speeds may vary or be slower (Starlink 'Slow Speeds - Outside/During Peak Hours').",
            "Plan-based deprioritization: Residential Lite data is 'always deprioritized' compared with other fixed plans, so it is slower in congested areas and at peak hours. Residential 100/200 Mbps and Roam customers are more likely to slow down during congestion than Residential Max. Priority data takes precedence over Residential and Roam (Service Plan Descriptions).",
            "Network management: if your bandwidth use consistently exceeds a typical residential user's, Starlink may reduce your speeds (Service Plan Descriptions / Fair Use Policy).",
            "Priority plans that run out of priority data drop to up to 1 Mbps download and 0.5 Mbps upload.",
            "Elevated packet loss from extreme weather, temporary network issues or obstructions (RECENT INTERRUPTIONS alert).",
            "Thermal throttling when the dish or power supply runs hot.",
            "Using Starlink away from its registered service location, or on Mobile/Roam service.",
            "Local problems: a VPN, the 2.4 GHz band or distance from the router, Ethernet cable below Cat5e, and third-party routers, mesh or switches."
        ],
        "slow_speed_help_url": "https://starlink.com/support/article/7cf0a30d-d72e-5228-84e7-83fa58821bb8",
        "recommended_steps": [
            "Turn off any VPN and run a speed test again.",
            "Check whether all devices are slow or just one. For a single Wi-Fi device, try the 5 GHz band close to the router, or split the 2.4/5 GHz networks in the app and reboot the router. For Ethernet, use Cat5e cable or better.",
            "Use the Advanced Speed Test in the Starlink app (Router to Internet, Device to Router, Device to Internet), on 5 GHz and close to the router.",
            "With a third-party router, connect a computer by Ethernet directly to the Starlink power supply, or bypass your router, to test.",
            "Remove third-party routers, mesh and switches, and test with only Starlink equipment.",
            "Compare your results with the Starlink availability map. Within about 10 Mbps of the listed speed is normal.",
            "Check the app home screen for outage, obstruction or hardware alerts. Make sure Starlink is at the service location on your account.",
            "Make sure nothing is covering or blocking the dish (dirt, debris). Use 'Check for Obstructions' and relocate if needed.",
            "Power cycle Starlink and the router.",
            "If speeds are still slow, submit a support ticket through the Starlink app."
        ],
        "support_url": "https://starlink.com/support",
        "notes": "Peak hours are typically 6pm-11pm local time. The Residential plans include unlimited data, but Residential Lite data is always deprioritized. The Starlink router doesn't support MAC filtering or port forwarding.",
        "sources": [
            "https://starlink.com/support/article/7cf0a30d-d72e-5228-84e7-83fa58821bb8",
            "https://starlink.com/support/article/b0db3f4b-bde5-156d-240d-ffd343f8f88d",
            "https://starlink.com/support/article/64009737-3768-0003-2838-4786c5a850ea",
            "https://starlink.com/support/article/5483745b-f8f0-d9c4-4d57-17c35a7c233a",
            "https://starlink.com/support/article/a0fe8d51-32f7-d2b9-d74a-801e31ad9f6a",
            "https://starlink.com/support/article/0b372c01-c692-8920-8396-ffb7f429aab1",
            "https://starlink.com/support/article/f9a1d602-9204-e70c-a780-f2619d99f9c7",
            "https://starlink.com/legal/documents/DOC-1728-44881-79",
            "https://starlink.com/legal/documents/DOC-1534-93560-72",
            "https://starlink.com/specifications",
            "https://starlink.com/support"
        ]
    }
]
