included:
  - WiFiOrISP
  - Packages/WiFiOrISPCore/Sources
  - Packages/WiFiOrISPCore/Tests
excluded:
  - Packages/WiFiOrISPCore/.build
opt_in_rules:
  - empty_count
  - first_where
  - sorted_imports
identifier_name:
  excluded: [x, y, id, ms, to, on, v4, v6]
