import Foundation

/// The numbers behind an ISP report, so they can be tested apart from the wording.
public struct ReportSummary: Equatable, Sendable {
    public struct Outage: Equatable, Sendable {
        public var start: Date
        /// Nil while the outage is still going on.
        public var end: Date?
        public var routerAnswered: Bool?

        public func duration(now: Date) -> TimeInterval {
            (end ?? now).timeIntervalSince(start)
        }
    }

    public var start: Date
    public var end: Date
    public var sampleCount: Int
    public var outages: [Outage]
    /// Share of measured time each side was the problem, 0...1.
    public var ispSlowShare: Double
    public var yourSideSlowShare: Double
    public var routerMedianMs: Double?
    public var internetMedianMs: Double?
    public var internetP95Ms: Double?
    public var internetLoss: Double
    public var networks: [String]
    public var speedTests: [SpeedTestResult]
    public var responsiveness: [ResponsivenessResult]

    /// Gaps longer than this (sleep, app not running) don't count as measured time.
    static let maxGap: TimeInterval = 120

    public init(log: Log, start: Date, end: Date) {
        self.start = start
        self.end = end
        sampleCount = log.samples.count

        var outages: [Outage] = []
        var openStart: Date?
        for event in log.events {
            switch event.kind {
            case .dropStarted:
                openStart = event.time
            case .dropEnded(let since, let routerAnswered):
                outages.append(Outage(start: since, end: event.time, routerAnswered: routerAnswered))
                openStart = nil
            default:
                break
            }
        }
        if let openStart {
            outages.append(Outage(start: openStart, end: nil, routerAnswered: nil))
        }
        self.outages = outages

        var ispTime = 0.0
        var yourTime = 0.0
        var measured = 0.0
        let samples = log.samples
        for index in samples.indices {
            let next = index + 1 < samples.count ? samples[index + 1].time : samples[index].time
            let weight = min(next.timeIntervalSince(samples[index].time), Self.maxGap)
            guard weight > 0 else { continue }
            let window = Array(samples[max(0, index - VerdictEngine.window + 1)...index])
            measured += weight
            switch VerdictEngine.evaluate(window, now: samples[index].time).side {
            case .isp: ispTime += weight
            case .yours: yourTime += weight
            case nil: break
            }
        }
        ispSlowShare = measured > 0 ? ispTime / measured : 0
        yourSideSlowShare = measured > 0 ? yourTime / measured : 0

        routerMedianMs = Statistics.median(samples.compactMap { $0.router?.ms })
        let internet = samples.compactMap(\.internet)
        let internetMs = internet.compactMap(\.ms)
        internetMedianMs = Statistics.median(internetMs)
        internetP95Ms = Statistics.percentile(internetMs, 0.95)
        internetLoss = internet.isEmpty ? 0 : Double(internet.filter(\.isLost).count) / Double(internet.count)

        var seen = Set<String>()
        networks = samples.compactMap { $0.wifi?.ssid }.filter { seen.insert($0).inserted }
        speedTests = log.events.compactMap { if case .speedTest(let result) = $0.kind { result } else { nil } }
        responsiveness = log.events.compactMap { if case .responsiveness(let result) = $0.kind { result } else { nil } }
    }

    public var ispOutages: [Outage] { outages.filter { $0.routerAnswered == true } }

    public func totalDowntime(now: Date) -> TimeInterval {
        outages.reduce(0) { $0 + $1.duration(now: now) }
    }
}

/// A plain-text report to send an ISP: what happened, when, and why it's on their side.
public enum ISPReport {
    public static func text(log: Log, start: Date, end: Date, generated: Date = Date(), timeZone: TimeZone = .current) -> String {
        let summary = ReportSummary(log: log, start: start, end: end)
        let time = Date.FormatStyle(date: .abbreviated, time: .shortened, timeZone: timeZone)
        func when(_ date: Date) -> String { date.formatted(time) }

        var lines: [String] = []
        lines.append("Connection report")
        lines.append(String(repeating: "=", count: 17))
        lines.append("Period: \(when(start)) to \(when(end)) (\(timeZone.identifier))")
        if !summary.networks.isEmpty {
            lines.append("Network: \(summary.networks.joined(separator: ", "))")
        }
        lines.append("Generated by WiFi or ISP (wifiorisp.com) on \(when(generated))")
        lines.append("")

        guard summary.sampleCount > 0 else {
            lines.append("No measurements were taken in this period.")
            return lines.joined(separator: "\n") + "\n"
        }

        lines.append("Summary")
        lines.append("-------")
        let isp = summary.ispOutages
        let downtime = Duration.seconds(summary.totalDowntime(now: end))
        lines.append("- Outages: \(summary.outages.count), \(format(downtime)) in total.")
        if !summary.outages.isEmpty {
            lines.append("  During \(isp.count) of them, my router kept answering while nothing past it did,")
            lines.append("  so the connection inside my home was working and the outage was on the ISP's side.")
        }
        lines.append("- Slow because of the ISP's side: \(percent(summary.ispSlowShare)) of the time measured.")
        lines.append("- Slow because of my home network: \(percent(summary.yourSideSlowShare)) of the time measured.")
        if let router = summary.routerMedianMs {
            lines.append("- Typical round trip to my router: \(ms(router)).")
        }
        if let internet = summary.internetMedianMs, let p95 = summary.internetP95Ms {
            lines.append("- Typical round trip to the internet: \(ms(internet)) (95th percentile \(ms(p95))).")
        }
        lines.append("- Internet probes lost: \(percent(summary.internetLoss)).")
        lines.append("")

        if !summary.outages.isEmpty {
            lines.append("Outages")
            lines.append("-------")
            for outage in summary.outages {
                let range = "\(when(outage.start)) to \(outage.end.map(when) ?? "ongoing")"
                let side = switch outage.routerAnswered {
                case true: "router answered throughout: ISP side"
                case false: "router or Wi-Fi was also down"
                case nil: "router not measured"
                }
                lines.append("- \(range), \(format(.seconds(outage.duration(now: end)))) (\(side))")
            }
            lines.append("")
        }

        if !summary.speedTests.isEmpty {
            lines.append("Speed tests (M-Lab NDT7)")
            lines.append("------------------------")
            for test in summary.speedTests {
                lines.append("- \(when(test.time)): \(mbps(test.downloadMbps)) down, \(mbps(test.uploadMbps)) up, server \(test.server)")
            }
            lines.append("")
        }

        if !summary.responsiveness.isEmpty {
            lines.append("Lag under load (IETF responsiveness test)")
            lines.append("-----------------------------------------")
            for test in summary.responsiveness {
                lines.append("- \(when(test.time)): \(test.rpm) RPM (\(test.grade.rawValue)), round trips went from "
                    + "\(ms(test.idleLatencyMs)) to \(ms(test.loadedLatencyMs)) under load")
            }
            lines.append("")
        }

        lines.append("How this was measured")
        lines.append("---------------------")
        lines.append("Every 5 to 30 seconds, my Mac timed a TCP handshake to my router and, at the same moment, to")
        lines.append("1.1.1.1 and 8.8.8.8. A handshake is one network round trip. When the router answers quickly but")
        lines.append("the internet doesn't, the delay is past the router. An outage starts after two missed probes")
        lines.append("in a row. \(summary.sampleCount) measurements were taken in this period.")
        return lines.joined(separator: "\n") + "\n"
    }

    static func format(_ duration: Duration) -> String {
        duration.formatted(.units(allowed: [.hours, .minutes, .seconds], width: .abbreviated, maximumUnitCount: 2))
    }

    static func percent(_ share: Double) -> String {
        share > 0 && share < 0.001 ? "<0.1%" : share.formatted(.percent.precision(.fractionLength(0...1)))
    }

    static func ms(_ value: Double) -> String { "\(Int(value.rounded())) ms" }

    static func mbps(_ value: Double) -> String { "\(Int(value.rounded())) Mbps" }
}

/// Every sample as CSV, for spreadsheets.
public enum SampleCSV {
    public static let header = "time,link,network,access_point,band,channel,signal_dbm,noise_dbm,snr_db,tx_rate_mbps,"
        + "router_ms,router_lost,internet_ms,internet_lost"

    public static func text(_ samples: [Sample]) -> String {
        let time = Date.ISO8601FormatStyle(timeZone: .current)
        var lines = [header]
        for sample in samples {
            let wifi = sample.wifi
            let fields: [String] = [
                sample.time.formatted(time),
                sample.link.rawValue,
                escape(wifi?.ssid ?? ""),
                wifi?.bssid ?? "",
                wifi?.band?.rawValue ?? "",
                wifi?.channel.map(String.init) ?? "",
                wifi.map { String($0.rssi) } ?? "",
                wifi.map { String($0.noise) } ?? "",
                wifi.map { String($0.snr) } ?? "",
                wifi.map { String(Int($0.txRate.rounded())) } ?? "",
                probeMs(sample.router),
                probeLost(sample.router),
                probeMs(sample.internet),
                probeLost(sample.internet)
            ]
            lines.append(fields.joined(separator: ","))
        }
        return lines.joined(separator: "\n") + "\n"
    }

    static func probeMs(_ probe: Probe?) -> String {
        probe?.ms.map { String(format: "%.1f", $0) } ?? ""
    }

    static func probeLost(_ probe: Probe?) -> String {
        probe.map { $0.isLost ? "1" : "0" } ?? ""
    }

    static func escape(_ field: String) -> String {
        guard field.contains(where: { ",\"\n".contains($0) }) else { return field }
        return "\"" + field.replacingOccurrences(of: "\"", with: "\"\"") + "\""
    }
}
