#!/usr/bin/env python3
"""Generates RouterMakerPrefixes.swift: which router makers own which MAC address prefixes.

    curl -sL https://standards-oui.ieee.org/oui/oui.csv -o /tmp/oui.csv
    python3 Scripts/generate-router-makers.py /tmp/oui.csv

Only makers of home routers and ISP gateways are kept. Apple and Motorola are left out on
purpose: their prefixes also cover phones, which show up as the router when tethering.
"""
import csv
import re
import sys

MAKERS = {
    "eero": r"^eero",
    "netgear": r"netgear",
    "tpLink": r"tp-link",
    "asus": r"asustek",
    "linksys": r"linksys",
    "ubiquiti": r"ubiquiti",
    "google": r"^google",
    "synology": r"synology",
    "commscope": r"commscope|^arris",
    "technicolor": r"technicolor|vantiva",
    "sagemcom": r"sagemcom",
    "askey": r"askey",
    "nokia": r"^nokia",
    "arcadyan": r"arcadyan",
    "calix": r"^calix",
    "humax": r"humax",
    "sercomm": r"sercomm",
    "hitron": r"hitron",
    "ubee": r"ubee",
    "compal": r"compal broadband",
    "spacex": r"space exploration",
}

prefixes = {key: [] for key in MAKERS}
for row in csv.reader(open(sys.argv[1], encoding="utf-8")):
    if row[0] != "MA-L":
        continue
    for key, pattern in MAKERS.items():
        if re.search(pattern, row[2], re.IGNORECASE):
            prefixes[key].append(row[1].upper())
            break

lines = [
    "// Generated by Scripts/generate-router-makers.py from the IEEE OUI registry. Don't edit by hand.",
    "// swiftlint:disable all",
    "",
    "extension RouterMaker {",
    "    /// MAC address prefixes (first three bytes, uppercase hex) for each maker.",
    "    static let prefixes: [RouterMaker: String] = [",
]
for key in MAKERS:
    lines.append(f'        .{key}: "{" ".join(sorted(prefixes[key]))}",')
lines += ["    ]", "}", ""]
out = "Packages/WiFiOrISPCore/Sources/WiFiOrISPCore/RouterMakerPrefixes.swift"
open(out, "w").write("\n".join(lines))
print(f"Wrote {sum(len(v) for v in prefixes.values())} prefixes to {out}")
